server: #定义端口号
  port: 8001

spring:
  application: #微服务名称
    name: cloud-payment-service
  datasource: #微服务连接的数据源
    druid:
      url: jdbc:mysql://localhost:3306/springcloud_payment?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Hongkong&allowPublicKeyRetrieval=true&verifyServerCertificate=false&useSSL=false&allowMultiQueries=true
      driver-class-name: com.mysql.jdbc.Driver
      username: root
      password: pass
      initial-size: 10
      max-active: 50
      min-idle: 10
      max-wait: 60000
      pool-prepared-statements: true
      max-pool-prepared-statement-per-connection-size: 20
      validation-query: SELECT 1 FROM DUAL
      test-on-borrow: false
      test-on-return: false
      test-while-idle: true
      time-between-eviction-runs-millis: 60000
      filters: stat,wall

mybatis:
  mapperLocations: classpath:mapper/*.xml #mybatis扫描的xml文件路径
  type-aliases-package: com.loafer.springcloud.entity #mybatis扫描的xml文件所对应的实体类


